- name: Deploy
  uses: appleboy/ssh-action@master
  with:
    host: ${{ secrets.HOST }}
    username: ${{ secrets.USERNAME }}
    key: ${{ secrets.SSH_PRIVATE_KEY }}
    script: |
      set -e

      export NVM_DIR="$HOME/.nvm"
      source "$NVM_DIR/nvm.sh"

      cd /var/www/todo_backend

      git pull origin main
      npm install

      pm2 restart todo_backend || pm2 start server.js --name todo_backend